/*FUNCIONALIDADES BASE DE DATOS CINE*/

/*SECCION CRISTIAN*/
--Prueba Push fsdmfjfosdjfjsdio
/*SECCION PAULA*/

/*SECCION MIGUEL*/

/*FUNCIONALIDADES GLOBALES ADICIONALES(OPCIONAL)*/
/*PRUEBA PULL*/
